version: '3'
services:
  app:
    build: .
    volumes:
      - ${VOL_APP:-.}/:/opt/www
    ports:
      - 9501:9501
  redis:
    image: redis
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306