# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### api-tags-list
GET http://{{host}}/api/tags/list?page=1&limit=11
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("test response", function () {
    client.assert(response.body.code === 0, 'reponse code not 0');
    client.assert(response.body.data.current_page === 1, 'current_page not 1');
    client.assert(response.body.data.per_page === 11, 'per_page not 11');
});
%}

### api-tags-list
GET http://{{host}}/api/tags/list?page=-1&limit=11
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("test response", function () {
    client.assert(response.body.code === 0, 'reponse code not 0');
    client.assert(response.body.data.current_page === 1, 'current_page not 1');
    client.assert(response.body.data.per_page === 11, 'per_page not 11');
});
%}
### api-tags-list
GET http://{{host}}/api/tags/list?page=-1&limit=100
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("test response", function () {
    client.assert(response.body.code === 0, 'reponse code not 0');
    client.assert(response.body.data.current_page === 1, 'current_page not 1');
    client.assert(response.body.data.per_page === 50, 'per_page not 50');
});
%}

###



